function T = transform(the)
the1 = the(1); the2 = the(2); the3 = the(3);
the4 = the(4); the5 = the(5); the6 = the(6);

l3 = 270;l4 = 90;l5 = 315;l6 = 40;l7 = 40;
d1 = 75;

T=...
[   sin(the6)*(cos(the4)*sin(the1) - cos(the2 + the3)*cos(the1)*sin(the4)) + cos(the6)*(cos(the5)*(sin(the1)*sin(the4) + cos(the2 + the3)*cos(the1)*cos(the4)) + sin(the2 + the3)*cos(the1)*sin(the5)), cos(the6)*(cos(the4)*sin(the1) - cos(the2 + the3)*cos(the1)*sin(the4)) - sin(the6)*(cos(the5)*(sin(the1)*sin(the4) + cos(the2 + the3)*cos(the1)*cos(the4)) + sin(the2 + the3)*cos(the1)*sin(the5)), sin(the2 + the3)*cos(the1)*cos(the5) - sin(the5)*(sin(the1)*sin(the4) + cos(the2 + the3)*cos(the1)*cos(the4)), cos(the1)*(d1 + l4*cos(the2 + the3) + l5*sin(the2 + the3) + l3*cos(the2)) - (l6 + l7)*(sin(the5)*(sin(the1)*sin(the4) + cos(the2 + the3)*cos(the1)*cos(the4)) - sin(the2 + the3)*cos(the1)*cos(the5))
  - cos(the6)*(cos(the5)*(cos(the1)*sin(the4) - cos(the2 + the3)*cos(the4)*sin(the1)) - sin(the2 + the3)*sin(the1)*sin(the5)) - sin(the6)*(cos(the1)*cos(the4) + cos(the2 + the3)*sin(the1)*sin(the4)), sin(the6)*(cos(the5)*(cos(the1)*sin(the4) - cos(the2 + the3)*cos(the4)*sin(the1)) - sin(the2 + the3)*sin(the1)*sin(the5)) - cos(the6)*(cos(the1)*cos(the4) + cos(the2 + the3)*sin(the1)*sin(the4)), sin(the5)*(cos(the1)*sin(the4) - cos(the2 + the3)*cos(the4)*sin(the1)) + sin(the2 + the3)*cos(the5)*sin(the1), (l6 + l7)*(sin(the5)*(cos(the1)*sin(the4) - cos(the2 + the3)*cos(the4)*sin(the1)) + sin(the2 + the3)*cos(the5)*sin(the1)) + sin(the1)*(d1 + l4*cos(the2 + the3) + l5*sin(the2 + the3) + l3*cos(the2))
                                                                                - cos(the6)*(cos(the2 + the3)*sin(the5) - sin(the2 + the3)*cos(the4)*cos(the5)) - sin(the2 + the3)*sin(the4)*sin(the6),                                                                               sin(the6)*(cos(the2 + the3)*sin(the5) - sin(the2 + the3)*cos(the4)*cos(the5)) - sin(the2 + the3)*cos(the6)*sin(the4),                                           - cos(the2 + the3)*cos(the5) - sin(the2 + the3)*cos(the4)*sin(the5),                                                              l4*sin(the2 + the3) - l5*cos(the2 + the3) + l3*sin(the2) - (cos(the2 + the3)*cos(the5) + sin(the2 + the3)*cos(the4)*sin(the5))*(l6 + l7)
                                                                                                                                                                                                     0,                                                                                                                                                                                                  0,                                                                                                             0,                                                                                                                                                                                                     1];
