function dMdei = Comp_dMdei( M,ei )
dMdei=([diff(M(1,1),ei),diff(M(1,2),ei),diff(M(1,3),ei),diff(M(1,4),ei),diff(M(1,5),ei),diff(M(1,6),ei);...
                diff(M(2,1),ei),diff(M(2,2),ei),diff(M(2,3),ei),diff(M(2,4),ei),diff(M(2,5),ei),diff(M(2,6),ei);...
                diff(M(3,1),ei),diff(M(3,2),ei),diff(M(3,3),ei),diff(M(3,4),ei),diff(M(3,5),ei),diff(M(3,6),ei);...
                diff(M(4,1),ei),diff(M(4,2),ei),diff(M(4,3),ei),diff(M(4,4),ei),diff(M(4,5),ei),diff(M(4,6),ei);...
                diff(M(5,1),ei),diff(M(5,2),ei),diff(M(5,3),ei),diff(M(5,4),ei),diff(M(5,5),ei),diff(M(5,6),ei);...
                diff(M(6,1),ei),diff(M(6,2),ei),diff(M(6,3),ei),diff(M(6,4),ei),diff(M(6,5),ei),diff(M(6,6),ei)]);
end