function J = JACOBIAN(the)
the1 = the(1);
the2 = the(2);
the3 = the(3);
the4 = the(4);
the5 = the(5);
the6 = the(6);
a1=75; a2=270; a3=90; d1=335; d4=295; d7=80;
J = ...
[ d4*sin(the1)*sin(the2)*sin(the3) - a2*sin(the1)*sin(the2) - d4*cos(the2)*cos(the3)*sin(the1) - a3*cos(the2)*sin(the1)*sin(the3) - a3*cos(the3)*sin(the1)*sin(the2) - d7*cos(the1)*sin(the4)*sin(the5) - a1*sin(the1) - d7*cos(the2)*cos(the3)*cos(the5)*sin(the1) + d7*cos(the5)*sin(the1)*sin(the2)*sin(the3) + d7*cos(the2)*cos(the4)*sin(the1)*sin(the3)*sin(the5) + d7*cos(the3)*cos(the4)*sin(the1)*sin(the2)*sin(the5), -cos(the1)*(d4*cos(the2)*sin(the3) - a3*cos(the2)*cos(the3) - a2*cos(the2) + d4*cos(the3)*sin(the2) + a3*sin(the2)*sin(the3) + d7*cos(the2)*cos(the5)*sin(the3) + d7*cos(the3)*cos(the5)*sin(the2) + d7*cos(the2)*cos(the3)*cos(the4)*sin(the5) - d7*cos(the4)*sin(the2)*sin(the3)*sin(the5)), -cos(the1)*(d4*cos(the2)*sin(the3) - a3*cos(the2)*cos(the3) + d4*cos(the3)*sin(the2) + a3*sin(the2)*sin(the3) + d7*cos(the2)*cos(the5)*sin(the3) + d7*cos(the3)*cos(the5)*sin(the2) + d7*cos(the2)*cos(the3)*cos(the4)*sin(the5) - d7*cos(the4)*sin(the2)*sin(the3)*sin(the5)), d7*sin(the5)*(cos(the1)*cos(the2)*sin(the3)*sin(the4) - cos(the4)*sin(the1) + cos(the1)*cos(the3)*sin(the2)*sin(the4)), d7*cos(the1)*sin(the2)*sin(the3)*sin(the5) - d7*cos(the1)*cos(the2)*cos(the3)*sin(the5) - d7*cos(the5)*sin(the1)*sin(the4) - d7*cos(the1)*cos(the2)*cos(the4)*cos(the5)*sin(the3) - d7*cos(the1)*cos(the3)*cos(the4)*cos(the5)*sin(the2),                                                                                                                                                          0;
  a1*cos(the1) + a2*cos(the1)*sin(the2) + d4*cos(the1)*cos(the2)*cos(the3) + a3*cos(the1)*cos(the2)*sin(the3) + a3*cos(the1)*cos(the3)*sin(the2) - d4*cos(the1)*sin(the2)*sin(the3) - d7*sin(the1)*sin(the4)*sin(the5) + d7*cos(the1)*cos(the2)*cos(the3)*cos(the5) - d7*cos(the1)*cos(the5)*sin(the2)*sin(the3) - d7*cos(the1)*cos(the2)*cos(the4)*sin(the3)*sin(the5) - d7*cos(the1)*cos(the3)*cos(the4)*sin(the2)*sin(the5), -sin(the1)*(d4*cos(the2)*sin(the3) - a3*cos(the2)*cos(the3) - a2*cos(the2) + d4*cos(the3)*sin(the2) + a3*sin(the2)*sin(the3) + d7*cos(the2)*cos(the5)*sin(the3) + d7*cos(the3)*cos(the5)*sin(the2) + d7*cos(the2)*cos(the3)*cos(the4)*sin(the5) - d7*cos(the4)*sin(the2)*sin(the3)*sin(the5)), -sin(the1)*(d4*cos(the2)*sin(the3) - a3*cos(the2)*cos(the3) + d4*cos(the3)*sin(the2) + a3*sin(the2)*sin(the3) + d7*cos(the2)*cos(the5)*sin(the3) + d7*cos(the3)*cos(the5)*sin(the2) + d7*cos(the2)*cos(the3)*cos(the4)*sin(the5) - d7*cos(the4)*sin(the2)*sin(the3)*sin(the5)), d7*sin(the5)*(cos(the1)*cos(the4) + cos(the2)*sin(the1)*sin(the3)*sin(the4) + cos(the3)*sin(the1)*sin(the2)*sin(the4)), d7*cos(the1)*cos(the5)*sin(the4) - d7*cos(the2)*cos(the3)*sin(the1)*sin(the5) + d7*sin(the1)*sin(the2)*sin(the3)*sin(the5) - d7*cos(the2)*cos(the4)*cos(the5)*sin(the1)*sin(the3) - d7*cos(the3)*cos(the4)*cos(the5)*sin(the1)*sin(the2),                                                                                                                                                          0;
                                                                                                                                                                                                                                                                                                                                                                                                                             0,              d4*sin(the2)*sin(the3) - d4*cos(the2)*cos(the3) - a3*cos(the2)*sin(the3) - a3*cos(the3)*sin(the2) - a2*sin(the2) - d7*cos(the2)*cos(the3)*cos(the5) + d7*cos(the5)*sin(the2)*sin(the3) + d7*cos(the2)*cos(the4)*sin(the3)*sin(the5) + d7*cos(the3)*cos(the4)*sin(the2)*sin(the5),              d4*sin(the2)*sin(the3) - a3*cos(the2)*sin(the3) - a3*cos(the3)*sin(the2) - d4*cos(the2)*cos(the3) - d7*cos(the2)*cos(the3)*cos(the5) + d7*cos(the5)*sin(the2)*sin(the3) + d7*cos(the2)*cos(the4)*sin(the3)*sin(the5) + d7*cos(the3)*cos(the4)*sin(the2)*sin(the5),                                                                                d7*cos(the2 + the3)*sin(the4)*sin(the5),                                                                            d7*cos(the2)*sin(the3)*sin(the5) + d7*cos(the3)*sin(the2)*sin(the5) - d7*cos(the2)*cos(the3)*cos(the4)*cos(the5) + d7*cos(the4)*cos(the5)*sin(the2)*sin(the3),                                                                                                                                                          0;
                                                                                                                                                                                                                                                                                                                                                                                                                             0,                                                                                                                                                                                                                                                                                    -sin(the1),                                                                                                                                                                                                                                                                     -sin(the1),                                                                                             cos(the2 + the3)*cos(the1),                                                                                                                                  cos(the1)*cos(the2)*sin(the3)*sin(the4) - cos(the4)*sin(the1) + cos(the1)*cos(the3)*sin(the2)*sin(the4), cos(the2 + the3)*cos(the1)*cos(the5) - sin(the5)*(sin(the1)*sin(the4) + cos(the1)*cos(the2)*cos(the4)*sin(the3) + cos(the1)*cos(the3)*cos(the4)*sin(the2));
                                                                                                                                                                                                                                                                                                                                                                                                                             0,                                                                                                                                                                                                                                                                                     cos(the1),                                                                                                                                                                                                                                                                      cos(the1),                                                                                             cos(the2 + the3)*sin(the1),                                                                                                                                  cos(the1)*cos(the4) + cos(the2)*sin(the1)*sin(the3)*sin(the4) + cos(the3)*sin(the1)*sin(the2)*sin(the4), cos(the2 + the3)*cos(the5)*sin(the1) - sin(the5)*(cos(the2)*cos(the4)*sin(the1)*sin(the3) - cos(the1)*sin(the4) + cos(the3)*cos(the4)*sin(the1)*sin(the2));
                                                                                                                                                                                                                                                                                                                                                                                                                             1,                                                                                                                                                                                                                                                                                             0,                                                                                                                                                                                                                                                                              0,                                                                                                      -sin(the2 + the3),                                                                                                                                                                                                               cos(the2 + the3)*sin(the4),                                                                                        - sin(the2 + the3)*cos(the5) - cos(the2 + the3)*cos(the4)*sin(the5)];
                                                                                                                                                                                                                                                                                                                                                                                                                         
k1 = a1 + a2*sin(the2) + d4*cos(the2)*cos(the3) + a3*cos(the2)*sin(the3) + a3*cos(the3)*sin(the2) - d4*sin(the2)*sin(the3) + d7*cos(the2)*cos(the3)*cos(the5) - d7*cos(the5)*sin(the2)*sin(the3) - d7*cos(the2)*cos(the4)*sin(the3)*sin(the5) - d7*cos(the3)*cos(the4)*sin(the2)*sin(the5);
k2 = d4*cos(the3) + a3*sin(the3) + d7*cos(the3)*cos(the5) - d7*cos(the4)*sin(the3)*sin(the5);
k3 = sin(the5);
